### ISSUE TITLE
Make `CLUSTER_BACKUP_IMAGE` configuration optional

### ISSUE THREAD

**Issue by chaudum** [crate/crate-operator#109]
The image should not be required, since the image is not public yet and the clusters may be configured without backups.

https://github.com/crate/crate-operator/blob/66d4b97f6feb04084d0d1fc1cbb9d5cb788ad17c/crate/operator/config.py#L46-L47

**Comment by chaudum** [comment]
Related issues: #35 and #46

**Comment by lukasbals** [comment]
Done in https://github.com/crate/crate-operator/pull/131

**Comment by lukasbals** [comment]
Done in: https://github.com/crate/crate-operator/pull/131
