### ISSUE TITLE
License Alternatives

### ISSUE THREAD

**Issue by remear** [crate/crate-operator#357]
The current license is AGPL v3. Many organizations prohibit the use of this license, barring the use of this operator.

Is there any interest in moving toward other licenses?

**Comment by SStorm** [comment]
In short - yes. We expect to do that in the near future, stay tuned.

**Comment by remear** [comment]
https://github.com/crate/crate-operator/commit/fe08d5178182c3c1fd6076df8674582ced054049 changed the license to Apache 2.0
