### ISSUE TITLE
Extend installation instructions with required privileges and deployment spec

### ISSUE THREAD

**Issue by MarkusH** [crate/crate-operator#73]
The [installation instructions](https://github.com/crate/crate-operator/blob/master/docs/source/installation.rst) are very, very basic. It's lacking a spec for the the required privileges as well as a `Deployment` spec documenting the deployment of the operator.

**Comment by schwendinger** [comment]
documentation is updated. -> closing the issue

**Comment by chaudum** [comment]
See also #110
