### ISSUE TITLE
Allow scaling down even when dynamic replicas have `-all`

### ISSUE THREAD

**Issue by MarkusH** [crate/crate-operator#84]
In a dynamic replica setting, such as `1-all`, the lower bound counts for CrateDB to stay green. In this case, a cluster is considered healthy if there are still two nodes: 1 as the primary node and 1 with the one minimum required replica. The scaling operation should account for that.

**Comment by ikerdna** [comment]
Hi, im  new in python, I don't really know a lot but I wana to learn, do you think this is easy? I will be able to complete? 😞 O don't really get what I have to do😅

**Comment by MarkusH** [comment]
Hi @ikerdna, thank you for your interest in contributing :slightly_smiling_face: 

This ticket is about the function [`parse_replicas`](https://github.com/crate/crate-operator/blob/657dd030f1208becb7fa6adb7958b256e651730a/crate/operator/scale.py#L33). The task is to change the function in a way, such that any input (variable name `r`), if it contains a `-`, uses the lower limit, instead of the upper limit.

Here are some examples:
| Input     | Current return value | Expected return value |
| --------- | -------------------- | --------------------- |
|     `'1'` |                    1 |                     1 |
|   `'all'` |  9223372036854775807 |   9223372036854775807 |
|   `'1-4'` |                    4 |                     1 |
| `'3-all'` |  9223372036854775807 |                     3 |

`9223372036854775807` is identical to `sys.maxsize`.
